site_name: PennCNV
site_url: http://penncnv.openbioinformatics.org/
repo_url: http://github.com/WangGenomicsLab/penncnv/
repo_name: GitHub
site_description: PennCNV software distribution site
site_author: Kai Wang, et al
site_favicon: favicon.ico
copyright: 2007-2017 PennCNV
google_analytics: ['UA-7565671-1', 'www.openbioinformatics.org/penncnv']

docs_dir: docs
#include_search: true
#use_absolute_urls: true
#use_directory_urls: false

pages:

- Home: 'index.md'
- User Guide:
    - 'Download PennCNV': 'user-guide/download.md'
    - 'Install PennCNV': 'user-guide/install.md'
    - 'Quick Start-Up Guide': 'user-guide/startup.md'
- Misc:
    - 'FAQ': 'misc/faq.md'
    - 'Version History': 'misc/version_history.md'
    - 'Credit': 'misc/credit.md'
    - 'How to Contribute': 'misc/contributing.md'





